/**
 * VitePress markdown-it plugin that replaces ```mermaid code fences
 * with <img> tags pointing to pre-rendered SVGs in /diagrams/.
 *
 * The SVGs are generated by scripts/render-mermaid.mjs (run as predocs:build).
 * This plugin only does the fence → img replacement at build time.
 */

import { createHash } from "node:crypto";
import type MarkdownIt from "markdown-it";

function contentHash(source: string): string {
  return createHash("sha256").update(source.trim()).digest("hex").slice(0, 12);
}

export function mermaidPlugin(md: MarkdownIt): void {
  const defaultFence =
    md.renderer.rules.fence ||
    ((tokens, idx, options, _env, self) => self.renderToken(tokens, idx, options));

  md.renderer.rules.fence = (tokens, idx, options, env, self) => {
    const token = tokens[idx];

    if (token.info.trim() === "mermaid") {
      const hash = contentHash(token.content);
      const svgPath = `/diagrams/${hash}.svg`;
      return `<figure class="mermaid-diagram"><img src="${svgPath}" alt="Diagram" /></figure>\n`;
    }

    return defaultFence(tokens, idx, options, env, self);
  };
}
